### ISSUE TITLE
Crashed when trying to use it

### ISSUE THREAD

**Issue by prafulrana** [dqminh/docker-flatten#1]
ubuntu@ip-10-0-2-232:~/docker-flatten$ time sudo go run main.go -t newUha49yqc-8opAAAz 8b3a34e05fc3
===> Flattenning image: 8b3a34e05fc3 into tag: newUha49yqc-8opAAAz
get histories of the current image
from the history, get list of images that formed the current image
recursively delete whiteouts and deleted files in /tmp/8b3a34e05fc3260411364
prepare archived contents
prepare a directory to build new image /tmp/newUha49yqc-8opAAAz463686643
copy archive file over
create dockerfile
panic: runtime error: slice bounds out of range [recovered]
    panic: runtime error: slice bounds out of range

goroutine 1 [running]:
text/template.errRecover(0x7fa75ba5ba08, 0x7fa75ba60100)
    /usr/lib/go/src/pkg/text/template/exec.go:84 +0xcd
----- stack segment boundary -----
main.finalImage.Cmds(0xf8400cd260, 0xc, 0x7fff28feb945, 0x13, 0x7fff28feb959, ...)
    /home/ubuntu/docker-flatten/main.go:51 +0x4f
main.finalImage.HasCmds(0xf8400cd260, 0xc, 0x7fff28feb945, 0x13, 0x7fff28feb959, ...)
    /home/ubuntu/docker-flatten/main.go:55 +0x34
main.(_finalImage).HasCmds(0xf8401add20, 0x0, 0x7fa75ba60100, 0x7fa75ba60fb8)
    /home/ubuntu/docker-flatten/main.go:0 +0x73
----- stack segment boundary -----
reflect.Value.call(0x5ec9b8, 0xf8401add20, 0x53a, 0x605674, 0x6c6c614300000004, ...)
    /usr/lib/go/src/pkg/reflect/value.go:521 +0x135e
reflect.Value.Call(0x5ec9b8, 0xf8401add20, 0x53a, 0x72f718, 0x0, ...)
    /usr/lib/go/src/pkg/reflect/value.go:334 +0x85
text/template.(_state).evalCall(0xf8400f41e0, 0x5ec9b8, 0xf8401add20, 0x192, 0x5ec9b8, ...)
    /usr/lib/go/src/pkg/text/template/exec.go:500 +0x7ee
text/template.(_state).evalField(0xf8400f41e0, 0x5ec9b8, 0xf8401add20, 0x192, 0x662ec7, ...)
    /usr/lib/go/src/pkg/text/template/exec.go:414 +0x2db
----- stack segment boundary -----
text/template.(_state).evalFieldChain(0xf8400f41e0, 0x5ec9b8, 0xf8401add20, 0x192, 0x5ec9b8, ...)
    /usr/lib/go/src/pkg/text/template/exec.go:387 +0x1aa
text/template.(_state).evalFieldNode(0xf8400f41e0, 0x5ec9b8, 0xf8401add20, 0x192, 0xf840068fe0, ...)
    /usr/lib/go/src/pkg/text/template/exec.go:365 +0xa7
text/template.(_state).evalCommand(0xf8400f41e0, 0x5ec9b8, 0xf8401add20, 0x192, 0xf840068fc0, ...)
    /usr/lib/go/src/pkg/text/template/exec.go:317 +0x284
text/template.(_state).evalPipeline(0xf8400f41e0, 0x5ec9b8, 0xf8401add20, 0x192, 0xf8400699c0, ...)
    /usr/lib/go/src/pkg/text/template/exec.go:295 +0xfd
text/template.(_state).walkIfOrWith(0xf8400f41e0, 0xf800000009, 0x5ec9b8, 0xf8401add20, 0x192, ...)
    /usr/lib/go/src/pkg/text/template/exec.go:162 +0x93
text/template.(_state).walk(0xf8400f41e0, 0x5ec9b8, 0xf8401add20, 0x192, 0xf8400a3580, ...)
    /usr/lib/go/src/pkg/text/template/exec.go:135 +0x40b
text/template.(_state).walk(0xf8400f41e0, 0x5ec9b8, 0xf8401add20, 0x192, 0xf840338c40, ...)
    /usr/lib/go/src/pkg/text/template/exec.go:138 +0x5f9
text/template.(*Template).Execute(0xf8400a3400, 0xf840069120, 0xf840082720, 0x5ec9a8, 0xf8401add20, ...)
    /usr/lib/go/src/pkg/text/template/exec.go:117 +0x1e3
main.buildImage(0xf840338980, 0x200000037, 0xf8400cd260, 0xc, 0x7fff28feb945, ...)
    /home/ubuntu/docker-flatten/main.go:142 +0x5ae
main.main()
    /home/ubuntu/docker-flatten/main.go:247 +0xce7

goroutine 2 [syscall]:
created by runtime.main
    /build/buildd/golang-1.0.2/src/pkg/runtime/proc.c:221

goroutine 3 [syscall]:
syscall.Syscall6()
    /build/buildd/golang-1.0.2/src/pkg/syscall/asm_linux_amd64.s:40 +0x5
syscall.EpollWait(0xf800000006, 0xf8400ae0c0, 0xa0000000a, 0xffffffff, 0xc, ...)
    /usr/lib/go/src/pkg/syscall/zerrors_linux_amd64.go:1781 +0xa1
net.(_pollster).WaitFD(0xf8400ae0b0, 0xf8400a37c0, 0x0, 0x0, 0x0, ...)
    /usr/lib/go/src/pkg/net/fd_linux.go:146 +0x110
net.(_pollServer).Run(0xf8400a37c0, 0x0)
    /usr/lib/go/src/pkg/net/fd.go:236 +0xe4
created by net.newPollServer
    /usr/lib/go/src/pkg/net/newpollserver.go:35 +0x382

goroutine 4 [chan receive]:
net.(_pollServer).WaitRead(0xf8400a37c0, 0xf84008a480, 0xf8400664b0, 0xb, 0x1, ...)
    /usr/lib/go/src/pkg/net/fd.go:268 +0x73
net.(_netFD).Read(0xf84008a480, 0xf8400b9000, 0x100000001000, 0xffffffff, 0xf8400690c0, ...)
    /usr/lib/go/src/pkg/net/fd.go:428 +0x1ec
net.(_TCPConn).Read(0xf8400823c8, 0xf8400b9000, 0x100000001000, 0xdaa00000000, 0x0, ...)
    /usr/lib/go/src/pkg/net/tcpsock_posix.go:87 +0xce
bufio.(_Reader).fill(0xf8400a3800, 0xf8400dc370)
    /usr/lib/go/src/pkg/bufio/bufio.go:77 +0xf0
bufio.(_Reader).Peek(0xf8400a3800, 0xf800000001, 0xf8400d1b01, 0x0, 0x0, ...)
    /usr/lib/go/src/pkg/bufio/bufio.go:102 +0xbc
net/http.(_persistConn).readLoop(0xf840095360, 0x0)
    /usr/lib/go/src/pkg/net/http/transport.go:525 +0xab
created by net/http.(*Transport).getConn
    /usr/lib/go/src/pkg/net/http/transport.go:382 +0x5df

goroutine 5 [finalizer wait]:
created by runtime.gc
    /build/buildd/golang-1.0.2/src/pkg/runtime/mgc0.c:882
exit status 2

**Comment by dqminh** [comment]
Thanks. I fixed the error in 3d72ab74be

It happens when the original image doesnt have any `CMD` specified. It was careless of me to not check :sweat_smile:
